use_frameworks!
target 'MainProject' do
  pod 'MediaService', :path => '../LocalRepo/MediaService'
  pod 'EL_ProtocolLib', :path => '../LocalRepo/EL_ProtocolLib'
  pod 'EL_MoudleBLib', :path => '../LocalRepo/EL_MoudleBLib'
  pod 'EL_MoudleALib', :path => '../LocalRepo/EL_MoudleALib'
end
